2019-03-21 00:43:52,678 INFO: MySQL startup [in E:\MySQL\app\__init__.py:47]
2019-04-02 23:59:33,202 INFO: MySQL startup [in E:\MySQL\app\__init__.py:47]
2019-04-17 21:35:58,088 INFO: MySQL startup [in E:\MySQL\app\__init__.py:47]
2019-04-17 21:36:10,752 INFO: MySQL startup [in E:\MySQL\app\__init__.py:47]
2019-04-17 21:39:39,763 INFO: MySQL startup [in E:\MySQL\app\__init__.py:47]
2019-04-17 21:43:02,050 INFO: MySQL startup [in E:\MySQL\app\__init__.py:47]
2019-04-17 22:08:59,195 INFO: MySQL startup [in E:\MySQL\app\__init__.py:47]
2019-04-17 22:09:00,477 ERROR: Exception on / [GET] [in E:\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\MySQL\app\routes.py", line 24, in index
    return render_template('MYSQL_base.html', title='Home')
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\MySQL\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: MYSQL_base.html
2019-04-17 22:09:02,913 ERROR: Exception on / [GET] [in E:\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\MySQL\app\routes.py", line 24, in index
    return render_template('MYSQL_base.html', title='Home')
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\MySQL\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: MYSQL_base.html
2019-04-17 22:09:04,922 ERROR: Exception on / [GET] [in E:\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\MySQL\app\routes.py", line 24, in index
    return render_template('MYSQL_base.html', title='Home')
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\MySQL\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: MYSQL_base.html
2019-04-17 22:09:05,937 ERROR: Exception on / [GET] [in E:\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\MySQL\app\routes.py", line 24, in index
    return render_template('MYSQL_base.html', title='Home')
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\MySQL\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\MySQL\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "E:\MySQL\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: MYSQL_base.html
